INSERT INTO Pelicula (
                         votos,
                         calificacion,
                         trailer,
                         imagen,
                         descripcion,
                         pais_origen,
                         actores,
                         director,
                         estreno,
                         duracion,
                         clasificacion,
                         genero,
                         titulo_original,
                         titulo
                         
                     )
                     VALUES (
                         NULL,
                         NULL,
                         'https://www.youtube.com/watch?v=BD77EOU8N3o&t=1s',
                         'https://i.ibb.co/6YthQDw/Shang-Chi.jpg',
                         'Adaptación cinematográfica del héroe creado por Steve Englehart y Jim Starlin en 1973, un personaje mitad chino, mitad americano, cuyo característico estilo de combate mezclaba kung-fu, nunchacos y armas de fuego.',
                         'United States of America',
                         'Simu Liu, Awkwafina, Tony Leung Chiu-Wai, Michelle Yeoh, Fala Chen, Florian Munteanu, Ronny Chieng',
                         'Destin Cretton',
                         '2021-09-02',
                         '132 Min',
                         '12+',
                         'ACCIÓN',
                         'Shang-Chi and the Legend of the Ten Rings',
                         'Shang-Chi y la leyenda de los diez anillos'
                         
                     ),
                     (
                         NULL,
                         NULL,
                         'https://www.youtube.com/watch?v=dDliKbT44wI',
                         'https://i.ibb.co/HKPtY0F/Leyenda-Viuda.png',
                         'En una zona densamente boscosa al norte de San Petersburgo, la gente ha estado desapareciendo durante tres décadas y los pocos cadáveres encontrados estaban desnudos. El 14 de octubre de 2017, un equipo de voluntarios salió al bosque en busca de un adolescente desaparecido. Pronto, se perdió toda comunicación con ellos. Los lugareños creen que fueron capturados por el mismo espíritu oscuro que se llevó a los demás. Lo llaman “la viuda coja”.',
                         'Russian Federation',
                         'Viktotiya Potemina, Anastasiya Gribova, Margarita Bychkova',
                         'direIvan Mininctor',
                         '2021-09-30',
                         '86 Min',
                         '12+',
                         'Terror',
                         'The Widow',
                         'La Leyenda de la Viuda'
                         
                     ),
                     (
                         NULL,
                         NULL,
                         'https://www.youtube.com/watch?v=PDU6B93ltds',
                         'https://i.ibb.co/hZZCXjW/Memoria.jpg',
                         'Jessica (Tilda Swinton) no puede dormir desde que un fuerte "bang" interrumpió su sueño al amanecer. Mientras visita a su hermana en Bogotá, se hace amiga de Agnes (Jeanne Balibar), una arqueóloga que estudia restos humanos descubiertos dentro de un túnel en construcción. Jessica viaja para encontrarse con Agnes en el lugar de excavación y, en un pueblo cercano, conoce a un pescador llamado Hernán (Elkin Díaz). Ambos comparten recuerdos junto al río y cuando el día llega a su fin, Jessica se despierta con una sensación de claridad.',
                         'Colombia, Thailand',
                         'Tilda Swinton, Elkin Díaz, Juan Pablo Urrego, Jeanne Balibar, Daniel Giménez Cacho, Daniel Toro, Agnes Brekke, Jerónimo Barón, Constanza Gutiérrez',
                         'Apichatpong Weerasethakul',
                         '2021-09-30',
                         '136 Min',
                         'Todos',
                         'Drama',
                         'Memoria',
                         'Memoria'
                         
                     ),
                     (
                         NULL,
                         NULL,
                         'https://www.youtube.com/watch?v=kCdjpKpACn0',
                         'https://i.ibb.co/YcNP8Rv/Sin-Tiempo-Para-Morir.jpg',
                         'En Sin Tiempo Para Morir, Bond ha dejado el servicio activo y disfruta de una vida tranquila en Jamaica. Su paz es efímera cuando su viejo amigo Félix Leiter de la CIA aparece pidiendo ayuda. La misión de rescatar a un científico secuestrado resulta ser mucho más traicionera de lo esperado, llevando a Bond a la pista de un misterioso villano armado con nueva tecnología peligrosa.',
                         'United Kingdom, United States of America',
                         'Daniel Craig, Ralph Fiennes, Naomie Harris, Rory Kinnear, Léa Seydoux, Ben Whishaw, Jeffrey Wright, Ana de Armas, Dali Benssalah, David Dencik, Lashana Lynch, Billy Magnussen y Rami Malek.',
                         'Cary Joji Fukunaga',
                         '2021-09-30',
                         '163 Min',
                         '12+',
                         'Acción',
                         'No Time to Die',
                         'Sin Tiempo para Morir'
                         
                     ),
                     (
                         NULL,
                         NULL,
                         'https://www.youtube.com/watch?v=rQm0m4vXNsc',
                         'https://i.ibb.co/7NsJgvb/Los-Locos-Addams.jpg',
                         'La escalofriante familia favorita de todos está de regreso en esta nueva secuela animada de comedia Los Locos Addams 2. En esta nueva película, Los Addams se enredan en aventuras chifladas y se ven envueltos en divertidísimos encuentros con todo tipo de personajes desprevenidos. Siempre manteniéndose fieles a ellos mismos, Los Locos Addams llevan su icónica espeluznante y excéntrica personalidad a donde sea que vayan.',
                         'United States of America',
                         'Charlize Theron, Oscar Isaac, Chloë Grace Moretz, Nick Kroll, Bette Midler, Snoop Dogg, Bill Hader y Javon “Wanna” Walton',
                         'Greg Tiernan, Laura Brousseau y Kevin Povlovic',
                         '2021-10-07',
                         '93 Min',
                         'Todos',
                         'Aventuras',
                         'Addams Family 2',
                         'Los Locos Addams 2'
                         
                     ),                     
                     (
                         NULL,
                         NULL,
                         'https://www.youtube.com/watch?v=8hvfgPkjsGk',
                         'https://i.ibb.co/XVtLY4m/Miss-Revolucion.jpg',
                         'Año 1970. Miss Mundo se celebra en Londres. Es el evento de televisión más visto del planeta. En plena transmisión, el recién creado Movimiento de Liberación de Mujeres interrumpe el programa afirmando que los concursos de belleza degradan a las mujeres. En contadas horas, la audiencia global es testigo del nacimiento de otro ideal de belleza.',
                         'France, United Kingdom',
                         'Keira Knightley, Gugu Mbatha-Raw, Jessie Buckley, Greg Kinnear',
                         'Philippa Lowthorpe',
                         '2021-10-07',
                         '106 Min',
                         '7+',
                         'Comedia',
                         'Misbehaviour',
                         'Miss Revolución'
                         
                     ),
                     (
                         NULL,
                         NULL,
                         'https://www.youtube.com/watch?v=wvQatiTAXEk&t=9s',
                         'https://i.ibb.co/M8qhfsZ/Venom.png',
                         'Eddie y Venom están luchando por coexistir cuando el simbionte más grande y malo se une con Cletus Kasady, un asesino en serie psicótico, desatando Carnage. Tom Hardy regresa a la pantalla grande como el protector letal Venom, uno de los personajes más grandes y complejos de MARVEL.',
                         'United States of America',
                         'Tom Hardy, Michelle Williams, Naomie Harris, Reid Scott, Stephen Graham y Woody Harrelson.',
                         'Andy Serkis',
                         '2021-10-07',
                         '90 Min',
                         '12+',
                         'Acción',
                         'Venom: Let There Be Carnage',
                         'Venom: Carnage Liberado'
                         
                     ),
                     (
                         NULL,
                         NULL,
                         'https://www.youtube.com/watch?v=SxQMByjUIPI',
                         'https://i.ibb.co/Wcnzr8S/Al-Limite.jpg',
                         'Lyz de 15 años, acaba de unirse a una prestigiosa escuela deportiva de esquí del Lycée de Bourg-Saint-Maurice. Fred, excampeón y ahora entrenador, decide apostarlo todo por su nueva integrante. Deslumbrada por su apoyo, Lyz pone su corazón y alma en ello, tanto física como emocionalmente. Conecta los éxitos, pero rápidamente cae bajo la influencia absoluta de Fred.',
                         'France',
                         'Noée Abita, Jérémie Rénier, Catherine Marchal, Muriel Combeau, François Godart',
                         'Charlène Favier',
                         '2021-10-14',
                         '92 Min',
                         '15+',
                         'Drama',
                         'Slalom',
                         'Al Límite'
                         
                     ),
                     (
                         NULL,
                         NULL,
                         'https://www.youtube.com/watch?v=go7dw9N8p-s',
                         'https://i.ibb.co/v4F4fpN/Chernobil.png',
                         'Tres protagonistas de la tragedia de Chernóbil entrecruzan sus vidas: un bombero, un ingeniero y un buzo militar. Cada uno intentará contener la radiación de la central nuclear y sobrellevar su drama personal, mientras descienden al mismísimo infierno para prevenir lo que podría ser el resultado más terrorífico de esta catástrofe, ocurrida en 1986.',
                         'Russian Federation',
                         'Danila Kozlovskiy, Flipp Avdeev, Samuel Tadevosian',
                         'Danila Kozlovskiy',
                         '2021-10-14',
                         '136 Min',
                         '12+',
                         'Drama',
                         'Chernobyl',
                         'Chernóbil: La Película'
                         
                     ),
                     (
                         NULL,
                         NULL,
                         'https://www.youtube.com/watch?v=8W1CvMT_MrA',
                         'https://i.ibb.co/sHdWgpF/El-Ultimo-Duelo.png',
                         'Una apasionante historia de traición y venganza enmarcada en la brutalidad y opresión femenina de la Francia del siglo XIV. La historia épica, basada en hechos reales descritos en el libro The Last Duel: A True Story of Crime, Scandal, and Trial by Combat in Medieval France, es protagonizada por el ganador de un Óscar® Matt Damon y el dos veces nominado a los premios Óscar® Adam Driver que interpretan a dos lords en disputa, ambos de noble cuna, que deben resolver sus agravios en un duelo a muerte.',
                         'United States of America',
                         'Matt Damon, Adam Driver, Jodie Comer y Ben Affleck',
                         'Ridley Scott',
                         '2021-10-14',
                         '152 Min',
                         '15+',
                         'Drama',
                         'The Last Duel',
                         'El Último Duelo'
                         
                     ),
                     (
                         NULL,
                         NULL,
                         'https://www.youtube.com/watch?v=5v3lPWNs7wY',
                         'https://i.ibb.co/r63RJS4/La-Noche-Bestia.png',
                         'El Jueves 28 de Febrero del 2008, IRON MAIDEN pisó nuestra tierra dando un concierto que marcó la vida de miles de fanáticos de la capital. ‘CHUKI’ (16) y VARGAS (17) han esperado este día por mucho tiempo, así se encaminan en una aventura por Bogotá sin esperar que un par de malandros les roben las boletas para el concierto. Un jueves que prometía ser el mejor día de sus jóvenes vidas, termina, potencialmente, siendo el peor.',
                         'Colombia, Mexico',
                         'Daniel Reyes, Esteban Galindo',
                         'Mauricio Leiva Cock',
                         '2021-10-14',
                         '73 Min',
                         '12+',
                         'Drama',
                         'La Noche de la Bestia',
                         'La Noche de la Bestia'
                         
                     ),
                     (
                         NULL,
                         NULL,
                         'https://www.youtube.com/watch?v=U6wuePVk0Ms',
                         'https://i.ibb.co/9sNz1MW/Peque-os-Mu-ecos-Diab-licos.png',
                         'Un niño encuentra accidentalmente a un creador de juguetes que le cuenta distintas historias. En la primera, un leprechaun busca vengarse de una familia indefensa. En la segunda, un muñeco aterroriza a su frágil dueño. El creador de juguetes regala al niño un payaso llamado Giggles. Aunque se supone que los payasos son los guardianes de la felicidad, estas criaturas maléficas causarán al joven un sinfín de noches sin dormir.',
                         'United States of America',
                         'Zach Galligan,Hannah Fierman, Piper Collins, Jonathan Horne, L.A. Winters, Courtney Lakin, Cory Anderson, Linda A. Zollo, Geoff McKnight',
                         'Matt Green',
                         '2021-10-14',
                         '86 Min',
                         '12+',
                         'Terror',
                         'Evil Little Things',
                         'Muñecos Diabólicos'
                     
                     );